version: '2'
catalog:
  name: "Postgres Replication"
  version: "v0.1"
  description: "Postgres Replication"
  questions:
    - variable: lb_port
      description: "Port to access PostgreSQL from external services"
      label: "Postgres LB Port"
      required: true
      default: 5432
      type: "int"
    - variable: postgres_db
      description: "Postgres Database"
      label: "Postgres Database"
      required: true
      default: "postgres_sb"
      type: "string"
    - variable: postgres_user
      description: "Postgres User"
      label: "Postgres User"
      required: true
      default: "postgres_user"
      type: "string"
    - variable: postgres_password
      description: "Postgres Password"
      label: "Postgres Password"
      required: true
      default: "postgres_password"
      type: "string"
    - variable: label_master
      label: "Host with Label to put LB Master on"
      description: |
        Example: 'postgres=master'
      required: false
      default: ""
      type: "string"
    - variable: label_slave_lb
      label: "Host with Label to put LB Slave on"
      description: |
        Example: 'postgres=slave_lb'
      required: false
      default: ""
      type: "string"
    - variable: label_slave_db
      label: "Host with Label to put DB Slave on"
      description: |
        Example: 'postgres=slave_db'
      required: false
      default: ""
      type: "string"
    - variable: postgres_scale
      description: "Number of postgres replication slaves."
      label: "Postgres scale:"
      required: true
      default: 3
      type: "int"

services:
  postgres-lb-master:
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - protocol: tcp
        service: postgres-master
        source_port: ${lb_port}
        target_port: 5432
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  postgres-lb-slave:
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - protocol: tcp
        service: postgres-slave
        source_port: ${lb_port}
        target_port: 5432
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  postgres-master:
    scale: 1
    health_check:
      port: 5432
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
  postgres-slave:
    scale: ${postgres_scale}
    health_check:
      port: 5432
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
