version: '2'
services:
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${pgadmin_email}
      PGADMIN_DEFAULT_PASSWORD: ${pgadmin_password}
{{- if ne .Values.host_label ""}}
    labels:
      io.rancher.scheduler.affinity:host_label: ${host_label}
{{- end}}
    ports:
      - "${port}:80"
