version: '2'
catalog:
  name: "Postgres"
  version: "v0.1"
  description: "PostgreSQL"
  questions:
    - variable: port
      description: "Port to access PostgreSQL from external services. No value means no external port."
      label: "Postgres Port"
      required: true
      default: 5432
      type: "int"
    - variable: postgres_db
      description: "Postgres Database"
      label: "Postgres Database"
      required: true
      default: "database1"
      type: "string"
    - variable: postgres_user
      description: "Postgres User"
      label: "Postgres User"
      required: true
      default: "user"
      type: "string"
    - variable: postgres_password
      description: "Postgres Password"
      label: "Postgres Password"
      required: true
      default: "password"
      type: "string"
    - variable: "POSTGRES_TAG"
      description: "The postgres tag to associate with this server"
      label: "Postgres tag"
      required: true
      default: "9.6-alpine"
      type: enum
      options: # List of options if using type of `enum`
        - latest
        - 10-alpine
        - 10
        - 9-alpine
        - 9
        - 9.6-alpine
        - 9.6
        - 9.5-alpine
        - 9.5
        - 9.4-alpine
        - 9.4
        - 9.3-alpine
        - 9.3
        - 9.2-alpine
        - 9.2
    - variable: host_label
      label: "Host with Label to put postgres on"
      description: |
        Host label to use as postgres 'value' tag.
        Example: 'postgres=true'
      required: false
      default: ""
      type: "string"

services:
  postgres:
    scale: 1
    health_check:
      port: 5432
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 2000
